@KdsApi_HostAddress = http://localhost:5261

GET {{KdsApi_HostAddress}}/Pedido/
Accept: application/json

###

POST {{KdsApi_HostAddress}}/Pedido/
Accept: application/json
Content-Type: application/json

{
    "MesaId": 1,
    "AtendenteId": 1,
    "ItensPedido": [
        {
            "ProdutoId": 1,
            "Quantidade": 2
        }
    ]
}

###

GET {{KdsApi_HostAddress}}/Pedido/1
Accept: application/json

###

POST {{KdsApi_HostAddress}}/Pedido/Fechar/1
Accept: application/json

###
